"""Azure-backed sandbox registry and lifecycle. One gateway replica / Uvicorn worker."""

import asyncio
import logging
import secrets
from contextlib import suppress
from datetime import timedelta

import httpx
from azure.core.exceptions import ResourceNotFoundError
from azure.data.tables import TableClient, UpdateMode
from azure.identity import ManagedIdentityCredential
from azure.mgmt.appcontainers import ContainerAppsAPIClient

from .policy import Settings, User, proxy_headers, reaper_decision, timestamp, utcnow

log = logging.getLogger("hls.gateway")


class BusyError(Exception):
    pass


class ActiveRunsError(Exception):
    pass


class ActivityUnavailableError(Exception):
    pass


class AzureRegistry:
    def __init__(self, settings, credential):
        self.table = TableClient(
            endpoint=f"https://{settings.storage_account}.table.core.windows.net",
            table_name="sandboxes", credential=credential,
        )

    def get(self, key):
        try:
            return dict(self.table.get_entity("sbx", key))
        except ResourceNotFoundError:
            return None

    def list(self):
        return [dict(row) for row in self.table.query_entities("PartitionKey eq 'sbx'")]

    def create(self, row):
        self.table.create_entity(row)

    def update(self, row):
        self.table.update_entity(row, mode=UpdateMode.MERGE)

    def delete(self, key):
        with suppress(ResourceNotFoundError):
            self.table.delete_entity("sbx", key)

    def close(self):
        self.table.close()


class AzureApps:
    def __init__(self, settings, credential):
        self.settings = settings
        self.client = ContainerAppsAPIClient(credential, settings.subscription_id)
        self.location = None

    def get(self, name):
        try:
            return self.client.container_apps.get(self.settings.resource_group, name).as_dict()
        except ResourceNotFoundError:
            return None

    def create(self, row):
        settings = self.settings
        if self.location is None:
            parts = settings.environment_id.split("/")
            environment = self.client.managed_environments.get(parts[4], parts[-1])
            self.location = environment.location
        self.client.container_apps.begin_create_or_update(
            settings.resource_group, row["app_name"], self.spec(row),
        ).result()

    def spec(self, row):
        settings = self.settings
        return {
            "location": self.location,
            "identity": {"type": "UserAssigned", "userAssignedIdentities": {settings.sandbox_identity_id: {}}},
            "properties": {
                "managedEnvironmentId": settings.environment_id,
                "configuration": {
                    "activeRevisionsMode": "Single",
                    "ingress": {"external": False, "targetPort": 7071, "transport": "auto", "allowInsecure": False},
                    "registries": [{"server": "acrhlsdeployer.azurecr.io", "identity": settings.sandbox_identity_id}],
                    "secrets": [{"name": "gateway-key", "value": row["gateway_key"]}],
                },
                "template": {
                    "containers": [{
                        "name": "sandbox", "image": settings.sandbox_image,
                        "resources": {"cpu": 2, "memory": "4Gi"},
                        "env": [
                            {"name": "HLS_HOSTED", "value": "1"},
                            {"name": "HLS_DATA_DIR", "value": "/data"},
                            {"name": "HLS_GATEWAY_KEY", "secretRef": "gateway-key"},
                            {"name": "HLS_SANDBOX_USER_EMAIL", "value": row["email"]},
                            {"name": "HLS_SANDBOX_USER_OID", "value": row["oid"]},
                            {"name": "HLS_SANDBOX_USER_TID", "value": row["tid"]},
                            {"name": "WARDFLOW_ROOT", "value": "/app/wardflow"},
                        ],
                        "volumeMounts": [{"volumeName": "sandboxes", "mountPath": "/data", "subPath": row["RowKey"]}],
                    }],
                    "scale": {"minReplicas": 1, "maxReplicas": 1},
                    "volumes": [{"name": "sandboxes", "storageType": "AzureFile", "storageName": "sandboxes",
                                 "mountOptions": "uid=10001,gid=10001,dir_mode=0750,file_mode=0640,nobrl,mfsymlinks,cache=strict"}],
                },
            },
        }

    def update_image(self, name, app):
        template = app["properties"]["template"]
        for container in template["containers"]:
            if container["name"] == "sandbox":
                container["image"] = self.settings.sandbox_image
        # A fresh suffix is generated by ACA; reusing an old suffix rejects the update.
        template.pop("revisionSuffix", None)
        self.client.container_apps.begin_update(
            self.settings.resource_group, name, {"properties": {"template": template}},
        ).result()

    def restart(self, name):
        revisions = self.client.container_apps_revisions.list_revisions(self.settings.resource_group, name)
        for revision in revisions:
            if revision.as_dict().get("properties", {}).get("active"):
                self.client.container_apps_revisions.restart_revision(self.settings.resource_group, name, revision.name)

    def delete(self, name):
        try:
            self.client.container_apps.begin_delete(self.settings.resource_group, name).result()
        except ResourceNotFoundError:
            pass

    def close(self):
        self.client.close()


class SandboxManager:
    def __init__(self, settings: Settings, registry, apps, http: httpx.AsyncClient):
        self.settings, self.registry, self.apps, self.http = settings, registry, apps, http
        # The deployment contract fixes maxReplicas=1 and the Docker command fixes workers=1.
        # Reserve the table row before provisioning so concurrent users cannot overbook slots.
        self.lock = asyncio.Lock()
        self.records = {}
        self.checked = set()
        self.pending_roll = set()
        self.tasks = {}
        self.last_write = {}

    def url(self, row):
        return f"https://{row['app_name']}.internal.{self.settings.environment_domain}"

    async def lookup(self, user):
        key = user.key
        if key not in self.records:
            row = await asyncio.to_thread(self.registry.get, key)
            if row is not None:
                self.records[key] = row
        row = self.records.get(key)
        # Even a truncated hash collision must never cross identity boundaries.
        if row is not None and (row["tid"] != user.tid or row["oid"] != user.oid):
            raise PermissionError("Sandbox identity mismatch")
        return row

    async def save(self, row, **changes):
        await asyncio.to_thread(self.registry.update, {"PartitionKey": "sbx", "RowKey": row["RowKey"], **changes})
        row.update(changes)

    def launch(self, row, operation):
        key = row["RowKey"]

        async def run():
            try:
                await operation()
            except Exception:
                log.exception("sandbox operation failed app=%s", row["app_name"])
                await self.save(row, state="error")
            finally:
                self.tasks.pop(key, None)

        self.tasks[key] = asyncio.create_task(run())

    async def ensure(self, user):
        async with self.lock:
            row = await self.lookup(user)
            if row is None:
                rows = await asyncio.to_thread(self.registry.list)
                if len(rows) >= self.settings.max_sandboxes:
                    raise BusyError("All sandboxes are in use. Please try again after someone finishes.")
                now = utcnow().isoformat()
                row = {
                    "PartitionKey": "sbx", "RowKey": user.key, "email": user.email,
                    "oid": user.oid, "tid": user.tid, "app_name": user.app_name,
                    "gateway_key": secrets.token_urlsafe(32), "created": now,
                    "last_seen": now, "state": "starting", "unreachable_since": "",
                }
                await asyncio.to_thread(self.registry.create, row)
                self.records[user.key] = row
                self.last_write[user.key] = utcnow()
            if user.key not in self.checked and user.key not in self.tasks:
                self.checked.add(user.key)
                if row["state"] == "deleting":
                    self.launch(row, lambda: self.remove(row))
                else:
                    # Reconcile the persisted app before proxying after a gateway restart.
                    await self.save(row, state="starting")
                    self.launch(row, lambda: self.provision(row))
            return row

    async def activity(self, row):
        user = User(row["email"], row["oid"], row["tid"])
        try:
            response = await self.http.get(
                self.url(row) + "/api/hosted/activity",
                headers=proxy_headers([], user, row["gateway_key"]), timeout=10,
            )
            response.raise_for_status()
            body = response.json()
            return body if isinstance(body, dict) else {}
        except (httpx.HTTPError, ValueError):
            return None

    async def healthy(self, row):
        try:
            response = await self.http.get(self.url(row) + "/api/health", timeout=5)
            return response.is_success
        except httpx.HTTPError:
            return False

    async def provision(self, row):
        app = await asyncio.to_thread(self.apps.get, row["app_name"])
        if app is None:
            await asyncio.to_thread(self.apps.create, row)
        else:
            image = next((c["image"] for c in app["properties"]["template"]["containers"] if c["name"] == "sandbox"), None)
            if image != self.settings.sandbox_image:
                activity = await self.activity(row)
                if activity is not None and type(activity.get("active_runs")) is int and activity["active_runs"] == 0:
                    await self.save(row, state="updating")
                    await asyncio.to_thread(self.apps.update_image, row["app_name"], app)
                    self.pending_roll.discard(row["RowKey"])
                else:
                    # Revisit on the next reaper pass, not while a run is in progress.
                    log.info("image update deferred app=%s: active or unknown work", row["app_name"])
                    self.pending_roll.add(row["RowKey"])
        await self.save(row, state="starting")

    async def touch(self, row):
        async with self.lock:
            key, now = row["RowKey"], utcnow()
            if row["state"] == "deleting":
                return
            previous = self.last_write.setdefault(key, timestamp(row["last_seen"]))
            row["last_seen"] = now.isoformat()
            if now - previous >= timedelta(minutes=1):
                await self.save(row, last_seen=now.isoformat())
                self.last_write[key] = now

    async def status(self, row):
        if row["state"] in {"ready", "deleting", "error"} or row["RowKey"] in self.tasks:
            return row["state"]
        healthy = await self.healthy(row)
        state = "ready" if healthy else "starting"
        if state != row["state"]:
            await self.save(row, state=state)
        return state

    async def change(self, user, action):
        async with self.lock:
            row = await self.lookup(user)
            if row is None:
                return
            if row["RowKey"] in self.tasks:
                raise BusyError("Your sandbox is already changing. Please wait.")
            activity = await self.activity(row)
            if activity is not None:
                active = activity.get("active_runs")
                if type(active) is not int or active < 0:
                    raise ActivityUnavailableError("Cannot confirm whether work is running. Try again shortly.")
                if active > 0:
                    raise ActiveRunsError("A run is active. Wait for it to finish before restarting or deleting.")
            elif action == "restart":
                raise ActivityUnavailableError("Cannot confirm whether work is running. Try again shortly.")
            await self.save(row, state="restarting" if action == "restart" else "deleting")
            if action == "restart":
                async def restart():
                    await asyncio.to_thread(self.apps.restart, row["app_name"])
                    self.checked.discard(row["RowKey"])
                    await self.save(row, state="starting")
                self.launch(row, restart)
            else:
                self.launch(row, lambda: self.remove(row))

    async def remove(self, row):
        await asyncio.to_thread(self.apps.delete, row["app_name"])
        await asyncio.to_thread(self.registry.delete, row["RowKey"])
        self.records.pop(row["RowKey"], None)
        self.checked.discard(row["RowKey"])
        self.pending_roll.discard(row["RowKey"])
        self.last_write.pop(row["RowKey"], None)
        log.info("deleted sandbox app=%s; Azure Files data retained", row["app_name"])

    async def reap(self):
        rows = await asyncio.to_thread(self.registry.list)
        for persisted in rows:
            async with self.lock:
                key = persisted["RowKey"]
                if key in self.tasks:
                    log.info("keep sandbox app=%s: lifecycle operation in progress", persisted["app_name"])
                    continue
                row = self.records.setdefault(key, persisted)
                if row["state"] == "deleting":
                    self.launch(row, lambda row=row: self.remove(row))
                    continue
                activity, now = await self.activity(row), utcnow()
                unreachable = timestamp(row["unreachable_since"]) if row.get("unreachable_since") else None
                if activity is None and unreachable is None:
                    unreachable = now
                    await self.save(row, unreachable_since=now.isoformat())
                elif activity is not None and unreachable is not None:
                    unreachable = None
                    await self.save(row, unreachable_since="")
                delete, reason = reaper_decision(
                    now=now, last_seen=timestamp(row["last_seen"]), idle_minutes=self.settings.idle_minutes,
                    activity=activity, unreachable_since=unreachable,
                )
                log.info("%s sandbox app=%s: %s", "reap" if delete else "keep", row["app_name"], reason)
                if delete:
                    await self.save(row, state="deleting")
                    self.launch(row, lambda row=row: self.remove(row))
                elif key not in self.checked or (
                    key in self.pending_roll and activity is not None
                    and type(activity.get("active_runs")) is int and activity["active_runs"] == 0
                ):
                    self.checked.add(key)
                    await self.save(row, state="starting")
                    self.launch(row, lambda row=row: self.provision(row))

    async def reaper_loop(self):
        while True:
            await asyncio.sleep(300)
            try:
                await self.reap()
            except Exception:
                log.exception("sandbox reaper pass failed")

    async def close(self):
        # Let in-flight Azure operations finish before closing their clients.
        if self.tasks:
            await asyncio.gather(*list(self.tasks.values()), return_exceptions=True)


def azure_services(settings):
    credential = ManagedIdentityCredential(client_id=settings.azure_client_id)
    return credential, AzureRegistry(settings, credential), AzureApps(settings, credential)
